version: "3.9"

services:
  my-redis-docker-service:
    image: redis:latest
    container_name: redis_container
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"
    networks:
      - app_network
    environment:
      - REDIS_URL=redis://my-redis-docker-service:6379

  backend:
    depends_on:
      my-redis-docker-service:
        condition: service_healthy
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://my-redis-docker-service:6379
    networks:
      - app_network
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "5173:5173"
    networks:
      - app_network
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_URL=http://backend:8080


networks:
  app_network:
    driver: bridge
